import {mkdirSync,mkdtempSync,cpSync,readFileSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(fileURLToPath(new URL('../',import.meta.url)));
const git=(...args)=>execFileSync('git',args,{cwd:root,encoding:'utf8'}).trim();
const commit=git('rev-parse','HEAD');
assert.equal(git('status','--porcelain'),'','请先提交项目修改，再打包确切的源码版本。');
const manifest=JSON.parse(readFileSync(path.join(root,'.openai/hosting.json'),'utf8'));
assert.ok(manifest.project_id);assert.equal(manifest.static?.directory,'dist');
mkdirSync(path.join(root,'.cache'),{recursive:true});
const stage=mkdtempSync(path.join(root,'.cache/site-package-'));
cpSync(path.join(root,'dist'),path.join(stage,'dist'),{recursive:true});
mkdirSync(path.join(stage,'dist/.openai'),{recursive:true});
writeFileSync(path.join(stage,'dist/.openai/hosting.json'),JSON.stringify(manifest,null,2)+'\n');
const archive=path.resolve(root,process.argv[2]??'.cache/exam-site.tar.gz');
const tar=process.platform==='win32'?path.join(process.env.SystemRoot??'C:/Windows','System32/tar.exe'):'tar';
execFileSync(tar,['-C',stage,'-czf',archive,'dist']);
const entries=execFileSync(tar,['-tzf',archive],{encoding:'utf8'}).trim().split(/\r?\n/);
assert.ok(entries.includes('dist/index.html'));assert.ok(entries.includes('dist/.openai/hosting.json'));
assert.ok(entries.every(p=>p.startsWith('dist/')&&!p.split('/').includes('..')));
assert.equal(git('rev-parse','HEAD'),commit);assert.equal(git('status','--porcelain'),'');
console.log(JSON.stringify({project_id:manifest.project_id,checkout_path:root,commit_sha:commit,archive,entries:entries.length}));
